name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create SSH Key File
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PUBLIC_KEY}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          echo "machine github.com login $GH_TOKEN" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform plan

          if [ $? -eq 0 ]; then
            git add .
            git commit -a -m "Auto commit by Github Actions"
            git push origin HEAD:main
          fi
